# Generated by Django 2.2 on 2020-01-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, verbose_name='用户名')),
                ('login_ip', models.CharField(max_length=16, verbose_name='登录ip')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
            ],
            options={
                'verbose_name': '登录日志',
                'verbose_name_plural': '登录日志',
                'db_table': 'login_log',
            },
        ),
    ]
